name: LapisChatCustomChannels
version: ${project.version}
api-version: "1.15"
main: net.lapismc.lapischat.customchannels.LapisChatCustomChannels
depend: [LapisChat]
softdepend: [LapisChatFactions]
authors: [Dart2112]
